### PR TITLE
Gotham Fix + AutoStart Service

### PR DESCRIPTION
**Pull request by Steveb1968**

### CODE REVIEW

**Comment by Lunatixz** [comment]
I'm still not sure I understand why you need all of those path changes?? The only thing that has changed from frodo to gotham when it comes to PTV is the json request... My pull only changes the problematic part of the code... which is the path directly used for json to access playlists.

Let me know what you think... I would like to keep the core coding as similar as possible. So if you implement this change over mine, I will do the same...

**Comment by Jasonra** [comment]
What is the actual change or requirement in Gotham that is causing problems?  I see that translatePath is showing some issues, but under what conditions?  Should it be removed from all places in the code?

**Comment by Lunatixz** [comment]
http://forum.xbmc.org/showthread.php?tid=68263&page=305
Posts 3043 to the end of post

Gotham has a security whitelist for jsons requests... so when PTV trys to query a playlist that is stored in addon_data it would fail... I had the issue fixed and merged so that addon_data is allowed to query. But translated paths won't work because it doesn't clear the whitelist.

So my gotham fix was to change only the path that PTV is trying to query rather then change all the paths in global.py

**Comment by Steveb1968** [comment]
The new security features in gotham seem to restrict addon's access to the file system in general unless it has been added as a source (video source or file manager source). A case in point is directory channels like bumpers/commercials, obliviously you don't what them as a video source but the addon can't access that folder unless it's added as a source in file manager. This security feature also affects json, minus some white listed paths but these paths must be direct paths and not translatePath and are usually read only. The fixes I made work both in gotham and frodo without any problems, bar the directory channels stated above(Gotham) and because a directory channel folder could be any ware in the file system I can't see a fix for coming in the form of a white list or in the code it's self. I only changed 4 lines of code and 2 of them where a better to be safe than sorry approach. ;)

**Comment by Lunatixz** [comment]
I can agree, rather safe then sorry.. I wasn't able to find any data concerning folders and security, docs for Gotham are limited!! So you are saying any translatedpaths will be blocked if it's not a source? your path changes correct this problem? and directory channels build fine? It could be that you just need to change the query path for directory request, just like I did with my change...

I'll wait for Jason to make the call, and will match his changes for symmetry.

**Comment by Steveb1968** [comment]
The only thing that isn't working as it should is the directory channel.

**Comment by Lunatixz** [comment]
I see now my change only worked with generated playlists not stored ones... Maybe you are right. A global change is safest.

**Comment by Lunatixz** [comment]
don't forget to update the addon.xml python dependent on version 2.1.0

**Comment by Lunatixz** [comment]
Are you going to pick apart all my improvements to Pseudo, this is very simiar to my icon notication. when i'm ready I will push my changes.

I overlooked the startup service, because it was your standalone plugin to start with... but the notification!!

**Comment by Steveb1968** [comment]
Nothing to do with your code! Just localizing some strings! (which should be done anyway) which you haven't I see! So take some time to check the changes before you jump on your hi horse.
Why on earth you think I would even look at you code is a joke!
Delusions of grandeur!

**Pull request closed without merging**
