### PR TITLE
Gotham Support, Videoparser tweak.

### PR DESCRIPTION
**Pull request by Lunatixz**

### CODE REVIEW

**Comment by Lunatixz** [comment]
Are you referring to the video parser or gotham support?
I'm not sure what to do with gotham, Since xbmc translate paths won't work... because of security exceptions in json requests... it has to be a direct link.

**Comment by Jasonra** [comment]
The mount and umount commands are not available on Windows.

**Comment by Jasonra** [comment]
Ah, I see that the paths for the mount and umount code require a posix platform, my bad.

**Comment by Jasonra** [comment]
Why is the code put into video parser directly? Why not put it into FileAccess so that everything can benefit from it?

**Comment by Lunatixz** [comment]
That's an oversight on my part... The problem was with accessing video during the parsing process... didn't really think past that.

Just ignore those changes, I was never able to test it anyway... But users reported it worked for them...

**Comment by Lunatixz** [comment]
I believe steveb's global approach is better. Covers stored playlists as well as generated ones. Please close this pull request.

**Pull request closed without merging**
